server:
  port: 8080
  servlet:
    context-path: /
spring:
  redis:
    host: 8.129.184.128
    port: 1288
    password: chuzimi888

ylh:
  jwt:
    # 密钥
    signKey: YLH
    ID: 1046762075
    subject: ${ylh.jwt.signKey}
    secretKey: xxxx
    exp: 1
    refreshToken: 86400
    claim:
      key: name
      value: ${ylh.jwt.signKey}